### ISSUE TITLE
Support Summary type.

### ISSUE THREAD

**Issue by songy23** [orijtech/promreceiver#5]
As a follow-up of https://github.com/orijtech/promreceiver/pull/4.

`Summary` is available in opencensus metrics package: https://github.com/census-instrumentation/opencensus-proto/blob/master/src/opencensus/proto/metrics/v1/metrics.proto#L262-L302.

**Comment by odeke-em** [comment]
@songy23 thank you for the report!

I started a move of this repository to the OpenCensus-Service in https://github.com/census-instrumentation/opencensus-service/pull/481 as I currently don't have
much bandwidth to work on this. Wanna first expedited merging that PR then the
current OpenCensus-Service maintainers can work on adding that support there?

**Comment by songy23** [comment]
SGTM. I'm tied up with some other work this week, will try to review that PR in the upcoming week.
